
source("global.R")

ui <- fluidPage(title = "rEEMSshiny",
                h2("Saved RData"),
                h4("Load an .RData file generated by eems.plots"),
                fileInput("file", NULL, accept = ".RData"),
                actionButton("go", "Proceed"),
                h2("Linked plots"),
                h4("Click and drag to select points on the plot"),
                fluidRow(
                  column(6,
                         h5("Dissimilarities between demes (alpha and beta)"),
                         plotOutput("plot1", brush = "plot_brush"))
                ),
                p("Each point in the dissimilarity scatter plot corresponds to a pair of demes, alpha and beta. When you select points in the dissimilarity scatter plot, they are highlighted in the geographic maps below."),
                fluidRow(
                  column(6, h5("Locations (alpha)"),plotOutput("plot2")),
                  column(6, h5("Locations (beta)"),plotOutput("plot3"))
                ),
                textOutput("summary")
)

server <- function(input, output) {
  
  data <- eventReactive(input$go, {
    validate(need(input$file, message = FALSE))
    load(input$file$datapath)
    B.component
  })
  dataWithSelection <- reactive({
    # need latest version of shiny to use req() function
    req(input$plot_brush)
    brushedPoints(data(), input$plot_brush, allRows = TRUE)
  })
  
  output$plot1 <- renderPlot({
    scatterPlotDist(data(), c("fitted", "obsrvd"))
  })
  
  output$plot2 <- renderPlot({
    scatterPlotDeme(dataWithSelection(), c("alpha.x", "alpha.y"))
  })
  
  output$plot3 <- renderPlot({
    scatterPlotDeme(dataWithSelection(), c("beta.x", "beta.y"))
  })
  
  output$summary <- renderText({
    sprintf("%d point(s) selected", 
            nrow(dplyr::filter(dataWithSelection(), selected_)))
  })
  
}

shinyApp(ui, server)
