# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resistance_distance <- function(M) {
    .Call('rEEMSplots_resistance_distance', PACKAGE = 'rEEMSplots', M)
}

rcppstandardize_rates <- function(tiles, rates, seeds, marks, distm) {
    .Call('rEEMSplots_rcppstandardize_rates', PACKAGE = 'rEEMSplots', tiles, rates, seeds, marks, distm)
}

rcppdont_standardize_rates <- function(tiles, rates, seeds, marks, distm) {
    .Call('rEEMSplots_rcppdont_standardize_rates', PACKAGE = 'rEEMSplots', tiles, rates, seeds, marks, distm)
}

