

function opt = default_params(sourcepath)


%% For MCMC sampling, set the total number of iterations as well as
%% the burn-in iterations (to discard at the start) and
%% the thinning step (to discard before saving an iteration)
opt = struct('numMCMCIter',{10000},...
	     'numBurnIter',{3000},...
	     'numThinIter',{30},...
             'mEffctHalfInterval',{2.4771},...
             'mrateMuHalfInterval',{2},...
	     'mEffctProposalS2',{0.1},...
	     'mSeedsProposalS2',{0.1},...
	     'mrateMuProposalS2',{0.01},...
	     'mrateShape',{0.001},...
	     's2locShape',{0.001},...
	     'mrateScale',{1},...
	     's2locScale',{1},...
	     'negBiSize',{5},...
	     'negBiProb',{1/2});
