

function opt = default_params(sourcepath)


%% For MCMC sampling, set the total number of iterations as well as
%% the burn-in iterations (to discard at the start) and
%% the thinning step (to discard before saving an iteration)
opt = struct('numMCMCIter',{10000},...
             'numBurnIter',{3000},...
             'numThinIter',{30},...
             'mEffctHalfInterval',{2.4771},...
             'qEffctHalfInterval',{0.1},...
             'mrateMuHalfInterval',{2},...
             'qrateMuHalfInterval',{1e-12},...
             'mSeedsProposalS2',{0.01},...
             'qSeedsProposalS2',{0.1},...
             'mEffctProposalS2',{0.1},...
             'qEffctProposalS2',{0.001},...
             'mrateMuProposalS2',{0.01},...
             'qrateMuProposalS2',{0.01},...
             'mrateShape',{0.001},...
             'qrateShape',{0.001},...
             's2locShape',{0.001},...
             'qrateScale',{1},...
             'mrateScale',{1},...
             's2locScale',{1},...
             'negBiSize',{10},...
             'negBiProb',{2/3});
